### ISSUE TITLE
input.py is not working with python3.4

### ISSUE THREAD

**Issue by sjs2109** [HyegeunCho/study_tensorflow#1]
converting input.py to python3 and running it, I got the error message as follows:

> Extracting /tmp/data/train-images-idx3-ubyte.gz
> /usr/lib/python3.4/gzip.py:372: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
>   chunk = self.extrabuf[offset: offset + size]
> /home/lovetube/study_tensorflow/aymericdamien/examples/2 - Basic Classifiers/input_data.py:35: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
>   data = data.reshape(num_images, rows, cols, 1)
> Extracting /tmp/data/train-labels-idx1-ubyte.gz
> Extracting /tmp/data/t10k-images-idx3-ubyte.gz
> Traceback (most recent call last):
>   File "nearest_neighbor.py", line 14, in <module>
>     mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)
>   File "/home/lovetube/study_tensorflow/aymericdamien/examples/2 - Basic Classifiers/input_data.py", line 134, in read_data_sets
>     test_images = extract_images(local_file)
>   File "/home/lovetube/study_tensorflow/aymericdamien/examples/2 - Basic Classifiers/input_data.py", line 33, in extract_images
>     buf = bytestream.read(rows \* cols \* num_images)
>   File "/usr/lib/python3.4/gzip.py", line 372, in read
>     chunk = self.extrabuf[offset: offset + size]
> TypeError: only integer arrays with one element can be converted to an index

**Comment by sjs2109** [comment]
change input_data.read_data_sets path  (/tmp/data/ --> MNIST_data)
